import org.gradle.kotlin.dsl.invoke

plugins {
    java
    application
    id("com.gradleup.shadow")
}

group = "me.carscupcake"
version = "0.0.11"

repositories {
    mavenCentral()
}

dependencies {
    implementation(project(":sbremake-data"))
    implementation("com.google.code.gson:gson:2.10.1")
    implementation("com.palantir.javapoet:javapoet:0.7.0")
    implementation(project(":"))
    implementation(project(":minestom"))
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}
application {
    mainClass.set("me.carscupcake.processor.Generators")
}

tasks.getByName<JavaExec>("run") {
    args = listOf(rootProject.projectDir.resolve("src/autogenerated/java").absolutePath)
}

tasks.shadowJar {
    mergeServiceFiles()
}
