name: Add to GitHub Releases

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set outputs
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "date_now=$(date +'%d.%m.%Y')" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - uses: gradle/actions/wrapper-validation@v4
      - name: Build with Gradle
        run: gradle build
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Add Jar to GitHub releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.TOKEN_GITHUB }}"
          automatic_release_tag: "${{ steps.vars.outputs.date_now }}-${{ steps.vars.outputs.sha_short }}"
          prerelease: true
          title: "Automatic Build - ${{ steps.vars.outputs.date_now }}-${{ steps.vars.outputs.sha_short }}"
          files: |
            target/SbRemake.jar
