name: Add to GitHub Releases

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set outputs
        id: vars
        run: |
          DATE=$(date +'%Y.%m.%d')
          echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
          echo "date_now=$DATE" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: gradle
      - name: Grant Gradlew Permissions
        run: chmod +x gradlew
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - uses: gradle/actions/wrapper-validation@v4
      - name: Build with Gradle
        run: gradle shadowJar
      
      - name: Add Jar to GitHub releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.TOKEN_GITHUB }}"
          automatic_release_tag: "Auto"
          prerelease: true
          title: "Automatic Build - ${{ steps.vars.outputs.date_now }}-${GITHUB_SHA::7}"
          files: |
            target/SbRemake.jar
